#Euler 2

#Problem:
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

#Author: Kshithij Iyer
#Date of creation: 12/1/2017

import time
#Recording start time of the program 000000
start=time.time()
#A variable to store the sum and to generate the series 
result=0
a,b=1,1
while 4000000>a:
    a,b=b,a+b
    if b%2==0:
        result=result+b
        #print(result)
print("Sum of all the even valued numbers till 4 million in fibonacci series is",result)
print("Execution time of program is",time.time()-start)
